### ISSUE TITLE
AttributeError: 'module' object has no attribute 'set_logging_level'

### ISSUE THREAD

**Issue by truetqy** [s-gupta/fast-rcnn#1]
While running sh experiments/train_models.sh, I got this error:

Traceback (most recent call last):
  File "tools/train_net.py", line 75, in <module>
    caffe.set_logging_level(0)
AttributeError: 'module' object has no attribute 'set_logging_level'

I followed the instructions to install caffe:
cd $FRCNN_ROOT
git clone https://github.com/rbgirshick/caffe-fast-rcnn.git caffe-fast-rcnn
cd caffe-fast-rcnn
git checkout fast-rcnn

And Make the file with -
USE_CUDNN := 1
WITH_PYTHON_LAYER := 1

Please advice.

**Comment by s-gupta** [comment]
You can safely comment it out (this just changes the GLOG logging level). I already did this and pushed the edits. Can you try now?

**Comment by truetqy** [comment]
@s-gupta yes. It's ok now. Thanks a lot!
