### ISSUE TITLE
Unable to download scripts

### ISSUE THREAD

**Issue by aku1506** [s-gupta/fast-rcnn#8]
Hi,

I cloned this github repository and tried to run the scripts provided in data section for download of init_models, nyud2_data amd nyud2_mcg_boxes.

> > 425 Failed to establish connection.
> > Error in server response, closing control connection.
> > Retrying.

I tried with --passive-ftp as well. But it doesn't help either.

Could you please check if ftp server is responding correctly!

**Comment by s-gupta** [comment]
The server looks to be down. If it does not come back up in a day, I will try to look for these files on my disk, upload them elsewhere and update the scripts. I will also reply back here. Sorry for the inconvenience and the delay.

**Comment by aku1506** [comment]
The server is down from last two weeks! So, it would be great if you could somehow share it on google drive. As i need it for my research work. It would be of great help!! :)

**Comment by s-gupta** [comment]
I am really sorry for the spotty availability of the ftp server. The server is up atleast for now. But I also copied the files [here](https://www.dropbox.com/sh/beku0purwugdp76/AAAytjrQuDvzFNJ9Orbqb1rIa?dl=0). Sorry for the inconvenience, let me know if you run into any issues.

**Comment by aku1506** [comment]
Thanks Saurabh! :) 
I appreciate your help.. :)

**Comment by jotaf98** [comment]
Thanks, the backup download was a life-saver! Just a suggestion, maybe link to it from the readme file for when the server is down.
